FROM node:22-alpine as Build

WORKDIR /app
COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

# --- DEPLOY ---

FROM nginx:stable-alpine AS Deploy

WORKDIR /

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

COPY --from=Build /app/dist app

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]